### ISSUE TITLE
Error message on convert

### ISSUE THREAD

**Issue by dflock** [sickill/coloration#12]
I'm getting an error trying to convert a tmTheme using the latest version of coloration:

```
duncan@duncan-desktop:~/dev$ tm2vim MadeToCode.tmTheme
/var/lib/gems/1.9.1/gems/color-tools-1.3.0/lib/color/rgb.rb:53:in `from_html': ArgumentError (ArgumentError)
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/color_rgba.rb:8:in `from_html'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/style.rb:26:in `block in initialize_from_hash'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/style.rb:18:in `each'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/style.rb:18:in `initialize_from_hash'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/style.rb:12:in `initialize'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/readers/textmate_theme_reader.rb:43:in `new'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/readers/textmate_theme_reader.rb:43:in `block in parse_input'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/readers/textmate_theme_reader.rb:29:in `each'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/readers/textmate_theme_reader.rb:29:in `parse_input'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/abstract_converter.rb:28:in `convert!'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/lib/coloration/abstract_converter.rb:13:in `process_cmd_line'
	from /var/lib/gems/1.9.1/gems/coloration-0.3.3/bin/tm2vim:5:in `<top (required)>'
	from /usr/local/bin/tm2vim:23:in `load'
	from /usr/local/bin/tm2vim:23:in `<main>'
```

The tmTheme file in question can be found here: https://raw.github.com/dflock/MadeToCode/master/MadeToCode.tmTheme

I'm not a ruby dev, so I have no idea how to fix this, sorry!

**Comment by gavinlaking** [comment]
Hi @dflock 
We've just push a fix to master for this issue. I ran the 'MadeToCode.tmtheme' through `tm2vim` just now and it appears to be converting correctly (as below). Hope that helps, and sorry you've waited over 2 years for a reply!

Gav

```
" Vim color file
" Converted from Textmate theme Made To Code using Coloration v0.3.3 (http://github.com/sickill/coloration)

set background=dark
highlight clear

if exists("syntax_on")
  syntax reset
endif

let g:colors_name = "Made To Code"

hi Cursor ctermfg=16 ctermbg=51 cterm=NONE guifg=#090916 guibg=#00ffff gui=NONE
hi Visual ctermfg=NONE ctermbg=24 cterm=NONE guifg=NONE guibg=#05438b gui=NONE
hi CursorLine ctermfg=NONE ctermbg=16 cterm=NONE guifg=NONE guibg=#1e1e29 gui=NONE
hi CursorColumn ctermfg=NONE ctermbg=16 cterm=NONE guifg=NONE guibg=#1e1e29 gui=NONE
hi ColorColumn ctermfg=NONE ctermbg=16 cterm=NONE guifg=NONE guibg=#1e1e29 gui=NONE
hi LineNr ctermfg=60 ctermbg=16 cterm=NONE guifg=#707077 guibg=#1e1e29 gui=NONE
hi VertSplit ctermfg=59 ctermbg=59 cterm=NONE guifg=#45454e guibg=#45454e gui=NONE
hi MatchParen ctermfg=203 ctermbg=NONE cterm=underline guifg=#ff3854 guibg=NONE gui=underline
hi StatusLine ctermfg=253 ctermbg=59 cterm=bold guifg=#d7d7d8 guibg=#45454e gui=bold
hi StatusLineNC ctermfg=253 ctermbg=59 cterm=NONE guifg=#d7d7d8 guibg=#45454e gui=NONE
hi Pmenu ctermfg=81 ctermbg=NONE cterm=NONE guifg=#6fd3ff guibg=NONE gui=NONE
hi PmenuSel ctermfg=NONE ctermbg=24 cterm=NONE guifg=NONE guibg=#05438b gui=NONE
hi IncSearch ctermfg=16 ctermbg=119 cterm=NONE guifg=#090916 guibg=#8fff58 gui=NONE
hi Search ctermfg=NONE ctermbg=NONE cterm=underline guifg=NONE guibg=NONE gui=underline
hi Directory ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi Folded ctermfg=59 ctermbg=16 cterm=NONE guifg=#54576b guibg=#090916 gui=NONE

hi Normal ctermfg=253 ctermbg=16 cterm=NONE guifg=#d7d7d8 guibg=#090916 gui=NONE
hi Boolean ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi Character ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi Comment ctermfg=59 ctermbg=16 cterm=NONE guifg=#54576b guibg=#090916 gui=NONE
hi Conditional ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi Constant ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi Define ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi DiffAdd ctermfg=253 ctermbg=64 cterm=bold guifg=#d7d7d8 guibg=#407d09 gui=bold
hi DiffDelete ctermfg=88 ctermbg=NONE cterm=NONE guifg=#850204 guibg=NONE gui=NONE
hi DiffChange ctermfg=253 ctermbg=17 cterm=NONE guifg=#d7d7d8 guibg=#142a4f gui=NONE
hi DiffText ctermfg=253 ctermbg=24 cterm=bold guifg=#d7d7d8 guibg=#204a87 gui=bold
hi ErrorMsg ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi WarningMsg ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi Float ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi Function ctermfg=81 ctermbg=NONE cterm=NONE guifg=#6fd3ff guibg=NONE gui=NONE
hi Identifier ctermfg=113 ctermbg=NONE cterm=NONE guifg=#99cf50 guibg=NONE gui=NONE
hi Keyword ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi Label ctermfg=119 ctermbg=16 cterm=NONE guifg=#8fff58 guibg=#0c151b gui=NONE
hi NonText ctermfg=17 ctermbg=16 cterm=NONE guifg=#282a32 guibg=#131320 gui=NONE
hi Number ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi Operator ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi PreProc ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi Special ctermfg=253 ctermbg=NONE cterm=NONE guifg=#d7d7d8 guibg=NONE gui=NONE
hi SpecialKey ctermfg=17 ctermbg=16 cterm=NONE guifg=#282a32 guibg=#1e1e29 gui=NONE
hi Statement ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi StorageClass ctermfg=113 ctermbg=NONE cterm=NONE guifg=#99cf50 guibg=NONE gui=NONE
hi String ctermfg=119 ctermbg=16 cterm=NONE guifg=#8fff58 guibg=#0c151b gui=NONE
hi Tag ctermfg=81 ctermbg=NONE cterm=NONE guifg=#6fd3ff guibg=NONE gui=NONE
hi Title ctermfg=253 ctermbg=NONE cterm=bold guifg=#d7d7d8 guibg=NONE gui=bold
hi Todo ctermfg=59 ctermbg=16 cterm=inverse,bold guifg=#54576b guibg=#090916 gui=inverse,bold
hi Type ctermfg=81 ctermbg=NONE cterm=NONE guifg=#6fd3ff guibg=NONE gui=NONE
hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline guifg=NONE guibg=NONE gui=underline
hi rubyClass ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi rubyFunction ctermfg=81 ctermbg=NONE cterm=NONE guifg=#6fd3ff guibg=NONE gui=NONE
hi rubyInterpolationDelimiter ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi rubySymbol ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi rubyConstant ctermfg=49 ctermbg=NONE cterm=NONE guifg=#00ffbc guibg=NONE gui=NONE
hi rubyStringDelimiter ctermfg=119 ctermbg=16 cterm=NONE guifg=#8fff58 guibg=#0c151b gui=NONE
hi rubyBlockParameter ctermfg=39 ctermbg=NONE cterm=NONE guifg=#239cff guibg=NONE gui=NONE
hi rubyInstanceVariable ctermfg=39 ctermbg=NONE cterm=NONE guifg=#239cff guibg=NONE gui=NONE
hi rubyInclude ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi rubyGlobalVariable ctermfg=39 ctermbg=NONE cterm=NONE guifg=#239cff guibg=NONE gui=NONE
hi rubyRegexp ctermfg=179 ctermbg=NONE cterm=NONE guifg=#e9c062 guibg=NONE gui=NONE
hi rubyRegexpDelimiter ctermfg=179 ctermbg=NONE cterm=NONE guifg=#e9c062 guibg=NONE gui=NONE
hi rubyEscape ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi rubyControl ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi rubyClassVariable ctermfg=39 ctermbg=NONE cterm=NONE guifg=#239cff guibg=NONE gui=NONE
hi rubyOperator ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi rubyException ctermfg=203 ctermbg=NONE cterm=NONE guifg=#ff3854 guibg=NONE gui=NONE
hi rubyPseudoVariable ctermfg=39 ctermbg=NONE cterm=NONE guifg=#239cff guibg=NONE gui=NONE
hi rubyRailsUserClass ctermfg=49 ctermbg=NONE cterm=NONE guifg=#00ffbc guibg=NONE gui=NONE
hi rubyRailsARAssociationMethod ctermfg=221 ctermbg=NONE cterm=NONE guifg=#f1d950 guibg=NONE gui=NONE
hi rubyRailsARMethod ctermfg=221 ctermbg=NONE cterm=NONE guifg=#f1d950 guibg=NONE gui=NONE
hi rubyRailsRenderMethod ctermfg=221 ctermbg=NONE cterm=NONE guifg=#f1d950 guibg=NONE gui=NONE
hi rubyRailsMethod ctermfg=221 ctermbg=NONE cterm=NONE guifg=#f1d950 guibg=NONE gui=NONE
hi erubyDelimiter ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi erubyComment ctermfg=59 ctermbg=16 cterm=NONE guifg=#54576b guibg=#090916 gui=NONE
hi erubyRailsMethod ctermfg=221 ctermbg=NONE cterm=NONE guifg=#f1d950 guibg=NONE gui=NONE
hi htmlTag ctermfg=74 ctermbg=NONE cterm=NONE guifg=#45c1ea guibg=NONE gui=NONE
hi htmlEndTag ctermfg=74 ctermbg=NONE cterm=NONE guifg=#45c1ea guibg=NONE gui=NONE
hi htmlTagName ctermfg=74 ctermbg=NONE cterm=NONE guifg=#45c1ea guibg=NONE gui=NONE
hi htmlArg ctermfg=74 ctermbg=NONE cterm=NONE guifg=#45c1ea guibg=NONE gui=NONE
hi htmlSpecialChar ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi javaScriptFunction ctermfg=113 ctermbg=NONE cterm=NONE guifg=#99cf50 guibg=NONE gui=NONE
hi javaScriptRailsFunction ctermfg=221 ctermbg=NONE cterm=NONE guifg=#f1d950 guibg=NONE gui=NONE
hi javaScriptBraces ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
hi yamlKey ctermfg=81 ctermbg=NONE cterm=NONE guifg=#6fd3ff guibg=NONE gui=NONE
hi yamlAnchor ctermfg=39 ctermbg=NONE cterm=NONE guifg=#239cff guibg=NONE gui=NONE
hi yamlAlias ctermfg=39 ctermbg=NONE cterm=NONE guifg=#239cff guibg=NONE gui=NONE
hi yamlDocumentHeader ctermfg=119 ctermbg=16 cterm=NONE guifg=#8fff58 guibg=#0c151b gui=NONE
hi cssURL ctermfg=39 ctermbg=NONE cterm=NONE guifg=#239cff guibg=NONE gui=NONE
hi cssFunctionName ctermfg=221 ctermbg=NONE cterm=NONE guifg=#f1d950 guibg=NONE gui=NONE
hi cssColor ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi cssPseudoClassId ctermfg=81 ctermbg=NONE cterm=NONE guifg=#6fd3ff guibg=NONE gui=NONE
hi cssClassName ctermfg=81 ctermbg=NONE cterm=NONE guifg=#6fd3ff guibg=NONE gui=NONE
hi cssValueLength ctermfg=85 ctermbg=NONE cterm=NONE guifg=#3bffbc guibg=NONE gui=NONE
hi cssCommonAttr ctermfg=167 ctermbg=NONE cterm=NONE guifg=#cf6a4c guibg=NONE gui=NONE
hi cssBraces ctermfg=NONE ctermbg=NONE cterm=NONE guifg=NONE guibg=NONE gui=NONE
```

**Comment by dflock** [comment]
Wow - totally forgotten about this! Better late then never :)
