### ISSUE TITLE
Error on conversion

### ISSUE THREAD

**Issue by david542542** [sickill/coloration#21]
Hi,

I am trying to convert the Mac Classic theme from TextMate to vim. However I get the following error:

```
LA-DEV-IM-MM:Themes david$ tm2vim Theme.xml
Ignoring ffi-1.9.25 because its extensions are not built.  Try: gem pristine ffi --version 1.9.25
Ignoring hitimes-1.3.0 because its extensions are not built.  Try: gem pristine hitimes --version 1.3.0
/Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/style.rb:29:in `block in initialize_from_hash': undefined method `caret=' for #<Coloration::Style:0x00007fb1de87aef0> (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/style.rb:19:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/style.rb:19:in `initialize_from_hash'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/style.rb:13:in `initialize'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/readers/textmate_theme_reader.rb:45:in `new'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/readers/textmate_theme_reader.rb:45:in `block in parse_input'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/readers/textmate_theme_reader.rb:31:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/readers/textmate_theme_reader.rb:31:in `parse_input'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/converters/abstract_converter.rb:26:in `process'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/lib/coloration/converters/abstract_converter.rb:14:in `process_cmd_line'
	from /Library/Ruby/Gems/2.3.0/gems/coloration-0.4.0/bin/tm2vim:8:in `<top (required)>'
	from /usr/local/bin/tm2vim:22:in `load'
	from /usr/local/bin/tm2vim:22:in `<main>'
```

Any idea on how I can fix it? Attached is the xml file I'm trying to convert.

[Theme.xml.zip](https://github.com/sickill/coloration/files/4485263/Theme.xml.zip)

**Comment by kzdev420** [comment]
Hello. David
I am Chis Sorin based on Romania from Upwork.
https://www.upwork.com/fl/chissorin2?s=1110580755107926016
I just saw your Upwork job post.
I recommend to run this command.

gem uninstall bundler
gem install bundler

gem install curb

or 

sudo gem pristine ffi
